### ISSUE TITLE
git2consul High availablity?

### ISSUE THREAD

**Issue by vigneshsenapathy** [Cimpress-MCP/git2consul#106] opened 2016-10-14 18:51 UTC
I am trying to install git2consul on a cluster and each time i try to install it on different nodes in a cluster one goes down. Is there any way for me to do HA for git2consul so that if one goes down we have some other node taking over for polling the changes

**Comment by poblahblahblah** [comment] 2016-10-17 22:40
A work around for this would be to use cron, git2consul with `-n` option (or the no daemon config directive), and a library that works with consul's built in distributed locks. Push this to all of your consul masters. For dealing with the locking mechanism we use https://github.com/goldstar/consul_do, but elsewhere I've also used https://github.com/zeroXten/consul-do.

example:
```
*/1 * * * * consul /usr/bin/consul-do /usr/bin/nodejs /opt/git2consul/index.js --config-file /etc/consul/git2consul.json $(/bin/hostname) && /usr/local/bin/consul-backup'
```

Hope this helps!

**Comment by vigneshsenapathy** [comment] 2016-10-18 01:03
Hey thanks for the this. One more question what do you mean consul masters? you mean consul leader? 

so i need to install consul-do and run the command to get high availability ?

**Comment by poblahblahblah** [comment] 2016-10-18 01:52
@vigneshsenapathy sorry for being unclear. By consul masters I meant consul servers, as opposed to consul clients.

The cronjob/consul-do based solution I proposed would need to be deployed to all of the consul servers. In my environment we have 5 consul servers per datacenter, so it would need to go to all 5 consul servers.

**Comment by calvn** [comment] 2016-10-18 03:09
@vigneshsenapathy are you able to grab the logs from the failed node?

**Comment by PedroAlvarado** [comment] 2016-10-18 03:39
@calvn What would you recommend for a git2consul HA setup? Or is @poblahblahblah's the best solution at the moment?

**Comment by calvn** [comment] 2016-10-18 04:08
We are running HA in production and haven't really experienced this issue, so that's why I was wondering if I could take a look at the logs. We are running three replicas (tasks) on ECS without passing the `-n` flag, running it via cron job, or performing consul locking. The only issue that I recall having that was HA-related was a problem with the config file being on the Consul KV, but I can't find the reference to the issue.

**Comment by vigneshsenapathy** [comment] 2016-10-18 15:18
@calvn @poblahblahblah : i am trying to run the below cron command i get the following error:
command:
consul /usr/bin/consul-do git2consul $(/bin/hostname) --config-file /etc/git2consul/git2consul_config/git2consul.json >>/var/log/git2consul/git2consul.log 2>&1

Error:
usage: consul [--version] [--help] <command> [<args>]

Available commands are:
    agent          Runs a Consul agent
    configtest     Validate config file
    event          Fire a new event
    exec           Executes a command on Consul nodes
    force-leave    Forces a member of the cluster to enter the "left" state
    info           Provides debugging information for operators
    join           Tell Consul agent to join cluster
    keygen         Generates a new encryption key
    keyring        Manages gossip layer encryption keys
    leave          Gracefully leaves the Consul cluster and shuts down
    lock           Execute a command holding a lock
    maint          Controls node or service maintenance mode
    members        Lists the members of a Consul cluster
    monitor        Stream logs from a Consul agent
    reload         Triggers the agent to reload configuration files
    rtt            Estimates network round trip time between nodes
    version        Prints the Consul version
    watch          Watch for changes in Consul

**Comment by poblahblahblah** [comment] 2016-10-18 15:40
@vigneshsenapathy the leading `consul` is the user that the cron job will execute as. If you are not running it in cron don't include it.

**Comment by vigneshsenapathy** [comment] 2016-10-18 15:53
@poblahblahblah : so i changed the user and now i am getting the following error:

/usr/lib/ruby/1.9.1/net/http.rb:763:in `initialize': Connection refused - connect(2) (Errno::ECONNREFUSED)
	from /usr/lib/ruby/1.9.1/net/http.rb:763:in `open'
	from /usr/lib/ruby/1.9.1/net/http.rb:763:in `block in connect'
	from /usr/lib/ruby/1.9.1/timeout.rb:55:in `timeout'
	from /usr/lib/ruby/1.9.1/timeout.rb:100:in `timeout'
	from /usr/lib/ruby/1.9.1/net/http.rb:763:in `connect'
	from /usr/lib/ruby/1.9.1/net/http.rb:756:in `do_start'
	from /usr/lib/ruby/1.9.1/net/http.rb:745:in `start'
	from /usr/lib/ruby/1.9.1/net/http.rb:1285:in `request'
	from /usr/lib/ruby/1.9.1/net/http.rb:1265:in `send_request'
	from /var/lib/gems/1.9.1/gems/consul_do-0.1.2/lib/consul_do.rb:28:in `http_put'
	from /var/lib/gems/1.9.1/gems/consul_do-0.1.2/lib/consul_do/elect.rb:36:in `create_session'
	from /var/lib/gems/1.9.1/gems/consul_do-0.1.2/lib/consul_do/elect.rb:42:in `session'
	from /var/lib/gems/1.9.1/gems/consul_do-0.1.2/lib/consul_do/elect.rb:79:in `get_lock'
	from /var/lib/gems/1.9.1/gems/consul_do-0.1.2/exe/consul-do:5:in `<top (required)>'
	from /usr/local/bin/consul-do:23:in `load'
	from /usr/local/bin/consul-do:23:in `<main>'

**Comment by vigneshsenapathy** [comment] 2016-10-18 16:13
@poblahblahblah : so i tried both the consul-do u mentioned.
Below is the 2nd one i tried which is https://github.com/zeroXten/consul-do.

**Command in the cronjob is :**

/usr/local/bin/consul-do git2consul $(/bin/hostname) --config-file /etc/git2consul_config/git2consul.json  >>/var/log/git2consul/git2consul.log 2>&1

**Error:**
Running...
Could not get datastore: <urlopen error [Errno 111] Connection refused>
Could not read KV store

**Comment by vigneshsenapathy** [comment] 2016-10-18 19:27
@poblahblahblah : i think i figured it out. In https://github.com/zeroXten/consul-do i had to change self.base_url to point to the server name and it worked.

**Comment by calvn** [comment] 2016-10-18 19:35
@vigneshsenapathy I performed a quick test on HA with git2consul on docker and didn't encounter any issues. I basically ran two containers with https://github.com/Cimpress-MCP/docker-git2consul under the same consul datacenter as the test. 

Can you provide the logs for the HA case were you were seeing the git2consul process fail on the node without cron?

**Comment by vigneshsenapathy** [comment] 2016-10-18 20:04
@calvn : so i installed https://github.com/zeroXten/consul-do and ran the cron job and i am seeing the following in the log:

Running...
Found KV store
Found session: f9189b56-4a18-95e4-604e-2fe6a58359ff
Found session node, we're the leader

And on the other hosts i get the following

Running...
Found KV store
Found session: f9189b56-4a18-95e4-604e-2fe6a58359ff
Found session node, we're not the leader

I think this is right ?

**Comment by calvn** [comment] 2016-10-18 20:43
I haven't used consul-do before, so can't really comment on that, and since that repo was last updated 2 years ago I would assume that it was created before locking mechanism was implemented directly in consul. 

If you are looking for locking functionality, I would suggest using [`consul lock`](https://www.consul.io/docs/commands/lock.html). You should be able to run it by doing something along the lines of `consul lock -verbose -token <your-token-if-any> /locks/git2consul git2consul ...`

**Comment by poblahblahblah** [comment] 2016-10-18 21:05
@calvn neat! I guess I need to read the consul release notes more carefully 👍

**Comment by vigneshsenapathy** [comment] 2016-10-18 21:08
@calvn : so i have 2 cron jobs running on 2 different hosts and here is what i am getting the error in one

{"name":"git2consul","hostname":"consul01","pid":24493,"level":50,"msg":"Failed to create repos due to Failed to load repo services-pixel-config due to Error: Error: Command failed: git clone -b master gitlab link master\nfatal: could not create work tree dir 'master'.: Permission denied\n fatal: could not create work tree dir 'master'.: Permission denied","time":"2016-10-18T21:06:01.434Z","v":0}

**Comment by calvn** [comment] 2016-10-18 21:16
Does the error always occur on the same node, or does it happen on different nodes from time to time as well? If it's always on the same node, it's likely that git2consul doesn't have permission to write to the particular directory it is using as the caching location. From a preliminary view at the log message, it doesn't look like the problem is caused by running git2consul in HA.

**Comment by vigneshsenapathy** [comment] 2016-10-19 01:10
@calvn : it was an error on one node only. I cleared the cache and it started working. It is working now. Thanks a lot for your help

**Comment by calvn** [comment] 2016-10-19 01:11
Awesome, glad it works now! I'll close this then.

**Closed by calvn** 2016-10-19 01:11 UTC
